// "use client";
import 'bootstrap/dist/css/bootstrap.css';
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './Components/Navbar';
import Footer from './Components/Footer';
// import ShoppingCart from './Components/ShoppingCart';
const inter = Inter({ subsets: ["latin"] });

import StoreProvider from './redux/StoreProvider';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
        <Navbar></Navbar>
        {children}
        {/* <ShoppingCart></ShoppingCart> */}
        <Footer></Footer>
        </StoreProvider>
      </body>
    </html>
  );
}
